image: python:3.12

variables:
    PYTHONUNBUFFERED: "1"

before_script:
  - pip install tox

stages: [precheck, test, deploy]

prechecks:
  tags: [ci.inria.fr, small]
  stage: precheck
  script:
  - pip install pre-commit
  - pre-commit run --all-files

pep8:
  tags: [ci.inria.fr, small]
  stage: test
  script:
  - tox -e pep8

docs:
  tags: [ci.inria.fr, small]
  stage: test
  script:
  - tox -e docs


#######################################################################################
#
# Functionnal tests:
#   - We boot a fresh instance of sharelatex and run test against it
#   - Test locally:
#     gitlab-runner exec docker \
#      --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
#      functionnal
#
#######################################################################################
py39-functional: &base-functional
  tags: [ci.inria.fr, large]
  stage: test
  image: python:3.9
  variables:
    TOXENV: py39
    SHARELATEX_IMAGE_VERSION: 5.2.1
    AUTH_TYPE: community
    DOCKER_ENV_FILE: env_overleaf
  script:
  # Install docker programs (docker-cli, docker-compose)
  - env
  - apt update
  - apt-get install -y ca-certificates curl
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian  bookworm stable" > /etc/apt/sources.list.d/docker.list
  - apt update
  - apt install -y docker-ce-cli  docker-compose-plugin  #  Install sharelatex
  - cd sharelatex/tests
  - export CI_SHARELATEX_IMAGE_VERSION="${SHARELATEX_IMAGE_VERSION}"
  - export CI_DOCKER_ENV_FILE="${DOCKER_ENV_FILE}"
  - docker compose up -d
  - sleep 10
  # FIXME: we need to force this as this is not ran by the entrypoint
  - docker exec -i mongo /bin/bash -c 'mongosh -u root -p root --authenticationDatabase admin < /docker-entrypoint-initdb.d/03_init_replSet.js'
  # Prepare the the functionnal tests
  # -create an user
  # -export the env variables needed by the tests
  # make sure the sharelatex container is correctly started ...
  - sleep 20
  - docker cp create-user-with-pass.js  sharelatex:/overleaf/services/web/modules/server-ce-scripts/scripts
  # user creation isn't idempotent
  #- docker exec sharelatex /bin/bash -ce "cd /overleaf/services/web && node modules/server-ce-scripts/scripts/create-user --admin --email=joe1@inria.fr"
  - docker exec --workdir /overleaf/services/web -i sharelatex node modules/server-ce-scripts/scripts/create-user-with-pass.js --email=joe1@inria.fr --pass=TestTest42
  - docker exec --workdir /overleaf/services/web -i sharelatex node modules/server-ce-scripts/scripts/create-user-with-pass.js --email=joe2@inria.fr --pass=TestTest42
  - docker exec --workdir /overleaf/services/web -i sharelatex node modules/server-ce-scripts/scripts/create-user-with-pass.js --email=joe3@inria.fr --pass=TestTest42
  - export CI_BASE_URL=http://172.17.0.1:8080
  - export CI_USERNAMES=joe1@inria.fr,joe2@inria.fr,joe3@inria.fr
  - export CI_PASSWORDS=TestTest42,TestTest42,TestTest42
  # let's test !
  # the python interpreter version is taken from the TOXENV var
  - tox
  # clean data base for local CI execution
  - docker exec -i mongo /bin/bash -c 'mongosh sharelatex -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "db.dropDatabase();"'

py310-functional:
  <<: *base-functional
  stage: test
  image: python:3.10
  variables:
    TOXENV: py310
    SHARELATEX_IMAGE_VERSION: 5.2.1
    DOCKER_ENV_FILE: env_overleaf
  allow_failure: true

py311-functional:
  <<: *base-functional
  stage: test
  image: python:3.11
  variables:
    TOXENV: py311
    SHARELATEX_IMAGE_VERSION: 5.2.1
    DOCKER_ENV_FILE: env_overleaf
  allow_failure: true

py312-functional:
  <<: *base-functional
  stage: test
  image: python:3.12
  variables:
    TOXENV: py312
    SHARELATEX_IMAGE_VERSION: 5.2.1
    DOCKER_ENV_FILE: env_overleaf
  allow_failure: true
########################################################################################
#
# Release zone:
#   - Create the wheel
#   - push it on pypi
#   - build and publish the doc
#
##########################################################################################
pages:
    stage: deploy
    tags: [ci.inria.fr, small]
    only:
    - tags
    script:
    - tox -e docs
    - mkdir -p public/
    - cp -r docs/_build/html/* public/
    artifacts:
      paths:
      - public

pypi:
    stage: deploy
    tags: [ci.inria.fr, small]
    only:
    - tags
    script:
    - pip install -r test-requirements.txt
    - python setup.py bdist_wheel
    - pip install twine
    # credentials are set in the env by gitlab
    - twine upload dist/* --verbose
